# Generated by Django 4.0.1 on 2022-03-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='regno',
            field=models.IntegerField(blank=True),
        ),
    ]
