# Generated by Django 4.0.1 on 2022-03-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_dashboard_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='regno',
            field=models.IntegerField(default='1234'),
        ),
    ]
