# Generated by Django 4.0.1 on 2022-03-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_dashboard_regno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='user',
            new_name='us',
        ),
    ]
