# Generated by Django 4.0.1 on 2022-03-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_user_dashboard_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
