# Generated by Django 4.0.1 on 2022-04-19 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_dashboard_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='sattapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(default='default/profile.jpg', upload_to='media/profileimages')),
                ('contactno', models.BigIntegerField(default='1000000000')),
                ('city', models.CharField(blank=True, max_length=25)),
                ('quali', models.CharField(blank=True, max_length=25)),
                ('workex', models.CharField(blank=True, max_length=25)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('cont', models.BigIntegerField(default='1000000000')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
