# Generated by Django 4.0.1 on 2022-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_sattapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='position',
            field=models.CharField(default='Student', max_length=30),
        ),
    ]
