# Generated by Django 4.0.1 on 2022-05-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_dashboard_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_rec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
