# Generated by Django 4.0.1 on 2022-05-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_dashboard_is_live_dashboard_is_rec_dashboard_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='profilepic',
            field=models.ImageField(default='media/default.jpg', upload_to='media/profileimages'),
        ),
    ]
