# Generated by Django 4.0.1 on 2022-05-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_dashboard_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='profilepic',
            field=models.ImageField(default='default.jpg', upload_to='media/profileimages'),
        ),
    ]
