# Generated by Django 4.0.1 on 2022-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_dashboard_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_afci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('profilepic', models.ImageField(default='default/profile.jpg', upload_to='media/profileimages')),
                ('contactno', models.BigIntegerField(default='1000000000')),
                ('city', models.CharField(blank=True, max_length=25)),
                ('quali', models.CharField(blank=True, max_length=25)),
                ('workex', models.CharField(blank=True, max_length=25)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('cv', models.FileField(upload_to='cv')),
                ('applyfor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='staff_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='sattapply',
        ),
    ]
