# Generated by Django 4.0.1 on 2022-06-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_apply_afci_staff_description_delete_sattapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_description',
            name='prf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.dashboard'),
            preserve_default=False,
        ),
    ]
