# Generated by Django 4.0.1 on 2022-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_staff_description_prf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='des',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='staff_description',
        ),
    ]
