# Generated by Django 4.0.1 on 2022-05-19 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_dashboard_position'),
        ('home', '0003_contact_alter_courses_duration_videolecture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=50)),
                ('scheduled', models.DateTimeField(auto_now_add=True, null=True)),
                ('teacher', models.CharField(max_length=50)),
                ('link', models.URLField(null=True)),
                ('bran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.branch')),
                ('c_ourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('msg', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('crs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
                ('prf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
