# Generated by Django 4.0.1 on 2022-05-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_courses_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='bran',
        ),
    ]
