# Generated by Django 4.0.1 on 2022-05-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='placement',
            name='wnumber',
            field=models.BigIntegerField(),
        ),
    ]
