# Generated by Django 4.0.1 on 2022-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_placement_number_alter_placement_wnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='subs_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
