# Generated by Django 4.0.1 on 2022-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_subs_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='fees',
            new_name='fees1',
        ),
        migrations.AddField(
            model_name='courses',
            name='fees2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='fees3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
