# Generated by Django 4.0.1 on 2022-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_fees1_courses_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
