# Generated by Django 4.0.1 on 2022-06-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_dashboard_des_delete_staff_description'),
        ('home', '0018_timetable_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='exdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_status', models.BooleanField(default=True)),
                ('crs', models.ManyToManyField(related_name='user', to='home.Courses')),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dashboard')),
            ],
        ),
    ]
