# Generated by Django 4.0.1 on 2022-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_exdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='exdb',
            name='dur',
            field=models.CharField(default='1mth', max_length=200),
        ),
    ]
