# Generated by Django 4.0.1 on 2022-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_exdb_dur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exdb',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
    ]
